# -*- coding: utf-8 -*-
"""Path_Choice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jc6RLMoKn6CwWvcBsqi9HnpEOZMXOpHD
"""

print("Welcome to the Path Choice!")

choice = input("Choose one of the paths by typing a letter, Path A, Path B, or Path C \n").lower()

if choice == "a":

    print("You chose Path A: It's a safe and peaceful path!")

    print("The End!")

elif choice == "b":

    print("You chose Path B: It's a dangerous and ugly path!")

    print("The End!")

elif choice == "c":

    print("You chose Path C: It's a normal path with nothing special!")

    print("The End!")

else:
    print("Typing error!")

    print("The End!")